# Generated by Django 5.1.6 on 2025-03-19 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='tweets',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='tweet.tweet'),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
